# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [backend/reset, backend/layout, backend/menuHeader, backend/menuLeft, backend/style, backend/tables, backend/forms, backend/tabber, backend/jquery-ui.custom.css, jscal/jscal2, jscal/border-radius, jscal/steel/steel, backend/inlinemedia.css]

  javascripts:    [backend/jquery, backend/tabber, backend/jquery-ui.custom.min.js, tiny_mce/jquery.tinymce.js, tiny_mce/tiny_mce, jscal/jscal2, jscal/lang/nl, jscal/lang/en]

  has_layout:     true
  layout:         layout
