<?php


/**
 * Skeleton subclass for representing a row from the 'btoproject' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 06:10:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Btoproject extends BaseBtoproject {

	/**
	 * Initializes internal state of Btoproject object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	public function __toString()
  	{
    	return $this->getName();
  	}
	
	public function isAssignedTo($userId)
	{
		$assignment = UserProjectPeer::retrieveByUserIdProjectId($userId, $this->getId());
		
		if(count($assignment) > 0)
			return true;
		else
			return false;
	}
	
	public function getAllEmployees()
	{
		$assignments = UserProjectPeer::retrieveByProjectId($this->getId());
		
		$employees = Array();
		
		if(count($assignments) > 0)
		{
			foreach($assignments as $assignment)
			{
				$employees[] = sfGuardUserProfilePeer::retrieveByUserId($assignment->getUserId());
			}
		}
		
		return $employees;
	}
	
	public function suspendAllComponents()
	{
		$comps = $this->getComponents();
		
		if(count($comps) > 0)
		{
			foreach($comps as $comp)
			{
				$comp->setState("I");
				$comp->save();
			}
		}
	}
} // Btoproject
