<?php


/**
 * Skeleton subclass for performing query and update operations on the 'btoproject' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 06:10:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BtoprojectPeer extends BaseBtoprojectPeer {
	public static function retrieveAll($pager=false)
	{
		$c = new Criteria();
		$c->addAscendingOrderByColumn(self::ID);
		
		$itemList = self::doSelect($c);
		
		if($pager)
		{
			return $c;
		}
		else
		{
			return self::doSelect($c);
		}
	}
	
	public static function retrieveByCompany($company=null, $addEmpty=false)
	{
		$c = new Criteria();
		$c->add(self::STATE, 'A');
		$c->add(self::COMPANY_ID, $company);
		$c->addAscendingOrderByColumn(self::NAME);	
		
		$itemList = self::doSelect($c);
		
		if($addEmpty)
		{
			$blank = array(new Btoproject());
			$itemList = array_merge($blank, $itemList);
		}
		
		return $itemList;
	}
	
	public static function retrieveAlsoInactiveByCompany($company=null, $addEmpty=false)
	{
		$c = new Criteria();
		$c->add(self::COMPANY_ID, $company);
		$c->addAscendingOrderByColumn(self::NAME);	
		
		$itemList = self::doSelect($c);
		
		if($addEmpty)
		{
			$blank = array(new Btoproject());
			$itemList = array_merge($blank, $itemList);
		}
		
		return $itemList;
	}
	
} // BtoprojectPeer
