<?php


/**
 * Skeleton subclass for performing query and update operations on the 'company' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 05:54:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CompanyPeer extends BaseCompanyPeer {

	public static function retrieveAll($pager=false)
	{
		$c = new Criteria();
		$c->add(self::STATE, 'A', Criteria::EQUAL);
		$c->addAscendingOrderByColumn(self::ID);
		
		$itemList = self::doSelect($c);
		
		if($pager)
		{
			return $c;
		}
		else
		{
			return self::doSelect($c);
		}
	}
	
	public static function retrieveAlsoInactive($pager=false)
	{
		$c = new Criteria();
		$c->addAscendingOrderByColumn(self::ID);
		
		$itemList = self::doSelect($c);
		
		if($pager)
		{
			return $c;
		}
		else
		{
			return self::doSelect($c);
		}
	}
	
	public static function getAllItems($addEmpty=false)
	{
		$c = new Criteria();
		$c->add(self::STATE, 'A', Criteria::EQUAL);
		$itemList = self::doSelect($c);
		
		if($addEmpty)
		{
			$blank = array(new Company());
			$itemList = array_merge($blank, $itemList);
		}
		
		return $itemList;
	}

} // CompanyPeer
