<?php


/**
 * Skeleton subclass for representing a row from the 'company' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 05:54:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Company extends BaseCompany {

	/**
	 * Initializes internal state of Company object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	public function __toString()
  	{
    	return $this->getName();
  	}
	
	public function retrieveSupervisorProfile()
	{
		$itemList = sfGuardUserProfilePeer::retrieveByCompanyId($this->id,true);
		return $itemList[0];
	}
	
	public function suspendAllProjects()
	{
		$projList = BtoprojectPeer::retrieveAlsoInactiveByCompany($this->getId());
		if(count($projList) > 0)
		{
			foreach($projList as $proj)
			{
				$proj->setState("I");
				$proj->save();
				
				$proj->suspendAllComponents();
			}
		}
	}
	
	public function suspendAllUsers()
	{
		$userList = sfGuardUserProfilePeer::retrieveByCompanyId($this->getId());
		if(count($userList) > 0)
		{
			foreach($userList as $user)
			{
				$user->setState("I");
				$user->save();
				
				$sfgUser = sfGuardUserPeer::retrieveByPK($user->getUserId());
				$sfgUser->setIsActive(0);
				$sfgUser->save();
				
			}
		}
	}

} // Company
