<?php


/**
 * Skeleton subclass for performing query and update operations on the 'component' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 05:56:56
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ComponentPeer extends BaseComponentPeer {
	public static function retrieveAll($pager=false)
	{
		$c = new Criteria();
		$c->addAscendingOrderByColumn(self::ID);
		
		$itemList = self::doSelect($c);
		
		if($pager)
		{
			return $c;
		}
		else
		{
			return self::doSelect($c);
		}
	}
	
	public static function retrieveByCompany($company=null, $addEmpty=false)
	{
		$userProfile = sfGuardUserProfilePeer::retrieveByUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
		$projects = BtoprojectPeer::retrieveByCompany($userProfile->getCompanyId());
			
		$c = new Criteria();
		$c->add(self::STATE, 'A');
		foreach($projects as $project):
			//print_r($project->getId());exit;
			$c->addOr(self::BTOPROJECT_ID, $project->getId());
		endforeach;
		$c->addAscendingOrderByColumn(self::NAME);	
		
		$itemList = self::doSelect($c);
		
		if($addEmpty)
		{
			$blank = array(new Btoproject());
			$itemList = array_merge($blank, $itemList);
		}
		
		return $itemList;
	}
} // ComponentPeer
