<?php


/**
 * Skeleton subclass for performing query and update operations on the 'hours' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 05:54:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class HoursPeer extends BaseHoursPeer {

	public static function retrieveByDateComponentUser($date, $component_id, $user_id)
	{
		$c = new Criteria();
		$c->add(self::STATE, 'A');
		$c->add(self::COMPONENT_ID, $component_id);
		$c->add(self::HOURDATE, $date);
		$c->add(self::USER_ID, $user_id);
		
		return self::doSelectOne($c);
	}
	
	public static function retrieveByDateUser($date, $user_id)
	{
		$c = new Criteria();
		$c->add(self::STATE, 'A');
		$c->add(self::HOURDATE, $date);
		$c->add(self::USER_ID, $user_id);
		return self::doSelect($c);
	}

} // HoursPeer
