<?php


/**
 * Skeleton subclass for performing query and update operations on the 'projectcomponent' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 05:54:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProjectcomponentPeer extends BaseProjectcomponentPeer {

} // ProjectcomponentPeer
