<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/20/12 12:44:33
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class sfGuardUserProfilePeer extends BasesfGuardUserProfilePeer {
	
	public static function retrieveByUserId($userId=null)
	{
		$c = new Criteria();
		//$c->add(self::STATE, 'A');
		$c->add(self::USER_ID, $userId);
		
		$itemList = self::doSelectOne($c);
		
		return $itemList;
	}
	
	public static function retrieveByCompanyId($companyId, $isSupervisor=false)
	{
		$c = new Criteria();
		//$c->add(self::STATE, 'A');
		$c->add(self::COMPANY_ID, $companyId);
		
		if($isSupervisor)
			$c->add(self::IS_SUPERVISOR, 1);
			
		$itemList = self::doSelect($c);
		
		return $itemList;
	}
	
	public static function retrieveActiveByCompanyId($companyId, $isSupervisor=false)
	{
		$c = new Criteria();
		$c->add(self::STATE, 'A');
		$c->add(self::COMPANY_ID, $companyId);
		
		if($isSupervisor)
			$c->add(self::IS_SUPERVISOR, 1);
		else
			$c->add(self::IS_SUPERVISOR, 0);
			
		$itemList = self::doSelect($c);
		
		return $itemList;
	}
	
	public static function retrieveAll()
	{
		$c = new Criteria();
		
		$itemList = self::doSelect($c);
		
		return $itemList;
	}
} // sfGuardUserProfilePeer
