<?php


/**
 * Skeleton subclass for representing a row from the 'user_project' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/28/12 13:28:12
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserProject extends BaseUserProject {

} // UserProject
