<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user_project' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 08/28/12 13:28:12
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserProjectPeer extends BaseUserProjectPeer {

	public static function retrieveByUserId($userId)
	{
		$c = new Criteria();
		$c->add(self::USER_ID, $userId);
	
		$itemList = self::doSelect($c);
		
		return $itemList;
	}
	
	public static function retrieveByProjectId($projectId)
	{
		$c = new Criteria();
		$c->add(self::PROJECT_ID, $projectId);
	
		$itemList = self::doSelect($c);
		
		return $itemList;
	}
	
	public static function retrieveByUserIdProjectId($userId,$projectId)
	{
		$c = new Criteria();
		$c->add(self::PROJECT_ID, $projectId);
		$c->add(self::USER_ID, $userId);
	
		$itemList = self::doSelect($c);
		
		return $itemList;
	}

} // UserProjectPeer
